CREATE DATABASE exercise1;
CREATE TABLE `exercise1`.`emp_1` (EMP_NUM CHAR(3),EMP_Lname VARCHAR(15) , 
EMP_FNAME VARCHAR(15) ,EMP_INITIAL CHAR(1), 
EMP_HIREDATE DATE , JOB_CODE CHAR(3) ,PRIMARY KEY (`EMP_NUM`));

INSERT INTO `exercise1`.`emp_1` (`EMP_NUM`, `EMP_Lname`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`)
 VALUES ('1', 'Thor', 'ROR', 'T', '2023-02-09', '101');
INSERT INTO `exercise1`.`emp_1` (`EMP_NUM`, `EMP_Lname`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`)
 VALUES ('2', 'Hulk', 'TAR', 'D', '2023-01-02', '102');
 